import { Router } from 'express';
import { dashboardRoutes } from '../modules/dashboard/dashboard.route.js';
import { productRoutes } from '../modules/product/product.route.js';
import { authRoutes } from '../modules/auth/auth.route.js';
import { productCategoryRoutes } from '../modules/category/product-category.route.js';
import { blogCategoryRoutes } from '../modules/category/blog-category.route.js';
import { blogRoutes } from '../modules/blog/blog.route.js';
import { uploadRoutes } from '../modules/upload/upload.route.js';
import { productTagRoutes } from '../modules/tag/product-tag.route.js';
import { blogTagRoutes } from '../modules/tag/blog-tag.route.js';
import { brandRoutes } from '../modules/brand/brand.route.js';
import { attributeRoutes } from '../modules/attribute/attribute.route.js';
import { adminRoutes } from '../modules/admin/admin.route.js';
import { shippingRoutes } from '../modules/shipping/shipping.route.js';
import { zoneRoutes } from '../modules/zone/zone.route.js';
import { zonePolicyRoutes } from '../modules/zone-policy/zone-policy.route.js';
import { webRoutes } from '../modules/web/web.route.js';
import { promoRoutes } from '../modules/promo/promo.route.js';
import { offerRoutes } from '../modules/offer/offer.route.js';
import { wishlistRoutes } from '../modules/wishlist/wishlist.route.js';
import { cartRoutes } from '../modules/cart/cart.route.js';
import { reviewRoutes } from '../modules/review/review.route.js';
import { orderRoutes } from '../modules/order/order.route.js';
import { customerRoutes } from '../modules/customer/customer.route.js';
import { notificationRoutes } from '../modules/notification/notification.route.js';
import { storeRoutes } from '../modules/store/store.route.js';
import { supplierRoutes } from '../modules/supplier/supplier.route.js';
import { stockRoutes } from '../modules/stock/stock.route.js';
import { stockTransferRoutes } from '../modules/stock-transfer/stock-transfer.route.js';
import { posRoutes } from '../modules/pos/pos.route.js';
const router = Router();

router.use('/products', productRoutes);
router.use('/auth', authRoutes);
router.use('/product-categories', productCategoryRoutes);
router.use('/blog-categories', blogCategoryRoutes);
router.use('/product-tags', productTagRoutes);
router.use('/blog-tags', blogTagRoutes);
router.use('/blogs', blogRoutes);
router.use('/uploads', uploadRoutes);
router.use('/attributes', attributeRoutes);
router.use('/brands', brandRoutes);
router.use('/shipping', shippingRoutes);
router.use('/zones', zoneRoutes);
router.use('/zone-policies', zonePolicyRoutes);
router.use('/admins', adminRoutes);
router.use('/web', webRoutes);
router.use('/promos', promoRoutes);
router.use('/offers', offerRoutes);
router.use('/wishlists', wishlistRoutes);
router.use('/carts', cartRoutes);
router.use('/reviews', reviewRoutes);
router.use('/orders', orderRoutes);
router.use('/customers', customerRoutes);
router.use('/notifications', notificationRoutes);
router.use('/stores', storeRoutes);
router.use('/suppliers', supplierRoutes);
router.use('/stocks', stockRoutes);
router.use('/stock-transfers', stockTransferRoutes);
router.use('/pos', posRoutes);

router.use('/dashboard', dashboardRoutes);

export const apiRoutes = router;

